# Generated by Django 5.2.6 on 2026-06-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(db_index=True, max_length=80, unique=True)),
                ('attach_no', models.CharField(blank=True, db_index=True, max_length=40)),
                ('kind', models.CharField(choices=[('INDENT', 'Indent'), ('TENDER', 'Tender'), ('BUDGET', 'Budget')], default='INDENT', max_length=10)),
                ('offer_type', models.CharField(choices=[('TO', 'TO (Technical Offer)'), ('TO_PI', 'TO & PI (Technical Offer + Proforma)')], default='TO', max_length=10)),
                ('year_month', models.CharField(max_length=6)),
                ('expert_code', models.CharField(max_length=20)),
                ('serial', models.PositiveIntegerField(db_index=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('order_no', models.CharField(blank=True, max_length=80)),
                ('client_commercial_expert', models.CharField(blank=True, max_length=120)),
                ('client_commercial_phone', models.CharField(blank=True, max_length=40)),
                ('client_technical_expert', models.CharField(blank=True, max_length=120)),
                ('client_technical_phone', models.CharField(blank=True, max_length=40)),
                ('price_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('BOTH', 'Internal & External')], default='INTERNAL', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, help_text='Required when the offer type is TO & PI.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WITH_TECHNICAL', 'With Technical'), ('RETURNED_TO_COMMERCIAL', 'Returned to Commercial'), ('WITH_SUPPLY', 'With Supply'), ('RETURNED_TO_TECHNICAL', 'Returned to Technical'), ('WITH_COMMERCIAL', 'With Commercial (final)'), ('UNSUP_PEND_SUP', 'Cannot supply — awaiting Supply manager'), ('UNSUP_PEND_COM', 'Cannot supply — awaiting Commercial manager'), ('UNSUPPLIABLE', 'Cannot supply'), ('UNSUP_CLOSED', 'Cannot supply'), ('PENDING_CANCEL', 'Cancel — pending approval'), ('CLOSED', 'Closed / Sent to client'), ('FINAL_APPROVED', 'Final Approved'), ('FINAL_CLOSED', 'Final Closed'), ('BURNED', 'Burned'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('holder_unit', models.CharField(blank=True, db_index=True, max_length=20)),
                ('upgraded_two_stage', models.BooleanField(default=False)),
                ('price_upgraded_two_stage', models.BooleanField(default=False)),
                ('split_active', models.BooleanField(default=False)),
                ('internal_status', models.CharField(blank=True, max_length=30)),
                ('external_status', models.CharField(blank=True, max_length=30)),
                ('internal_holder', models.CharField(blank=True, max_length=20)),
                ('external_holder', models.CharField(blank=True, max_length=20)),
                ('awaiting_approval', models.BooleanField(default=False)),
                ('proposed_action', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Expert currently working the case inside Technical/Supply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('supply_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_cases', to=settings.AUTH_USER_MODEL)),
                ('supply_external_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_external_cases', to=settings.AUTH_USER_MODEL)),
                ('supply_internal_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_internal_cases', to=settings.AUTH_USER_MODEL)),
                ('technical_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_cases', to=settings.AUTH_USER_MODEL)),
                ('technical_external_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_external_cases', to=settings.AUTH_USER_MODEL)),
                ('technical_internal_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_internal_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Case created'), ('SUBMIT_TO_TECHNICAL', 'Submitted to Technical'), ('RETURN_TO_COMMERCIAL', 'Returned to Commercial'), ('ASSIGN', 'Assigned to expert'), ('SEND_TO_SUPPLY', 'Submitted to Supply'), ('RETURN_TO_TECHNICAL', 'Returned to Technical'), ('SEND_TO_COMMERCIAL', 'Submitted to Commercial'), ('BUILD_TO', 'TO form built'), ('BUILD_PI', 'PI form built'), ('NEW_VERSION', 'New form version'), ('EDIT', 'Edited'), ('COMMENT', 'Comment added'), ('CLOSE', 'Closed — sent to client'), ('CANNOT_SUPPLY', 'Marked cannot supply'), ('APPROVE_UNSUPPLIABLE', 'Cannot-supply approved'), ('REJECT_UNSUPPLIABLE', 'Cannot-supply rejected'), ('RETURN_TO_SUPPLY', 'Returned to Supply'), ('FINALIZE', 'Final Approved'), ('REQUEST_CANCEL', 'Cancellation requested'), ('APPROVE_CANCEL', 'Cancellation approved'), ('REJECT_CANCEL', 'Cancellation rejected'), ('CANCEL', 'Cancelled'), ('BURN', 'Burned'), ('FINAL_CLOSE', 'Final Closed')], max_length=30)),
                ('from_unit', models.CharField(blank=True, max_length=20)),
                ('to_unit', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('form_kind', models.CharField(blank=True, max_length=10)),
                ('form_version', models.IntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, db_index=True, max_length=10)),
                ('two_stage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INQUIRY', 'Inquiry'), ('TO', 'Technical Offer (TO)'), ('PI', 'Proforma Invoice (PI)')], db_index=True, max_length=10)),
                ('side', models.CharField(blank=True, db_index=True, max_length=10)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('table', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('sent', models.BooleanField(default=False)),
                ('unit_at_creation', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, help_text='User whose signature/approval is stamped on this form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_experts', models.ManyToManyField(blank=True, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.client'),
        ),
        migrations.CreateModel(
            name='ExpertCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('client_row', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('quantity', models.CharField(blank=True, max_length=40)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='cases.case')),
            ],
            options={
                'ordering': ['case', 'row_no'],
                'unique_together': {('case', 'row_no')},
            },
        ),
    ]
