# Generated by Django 5.2 on 2026-07-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseform_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # two_stage + CaseExportLog already exist in the live DB (added outside
        # this migration history). Keep them in migration *state* only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='caseform',
                    name='two_stage',
                    field=models.BooleanField(default=False),
                ),
                migrations.CreateModel(
                    name='CaseExportLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('form_kind', models.CharField(blank=True, max_length=10)),
                        ('form_version', models.IntegerField(blank=True, null=True)),
                        ('side', models.CharField(blank=True, max_length=10)),
                        ('fmt', models.CharField(blank=True, max_length=20)),
                        ('label', models.CharField(blank=True, max_length=120)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_exports', to=settings.AUTH_USER_MODEL)),
                        ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='cases.case')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('rial_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_builtin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
