# Generated by Django 5.2 on 2026-07-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseform_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ``CaseForm.two_stage`` and ``CaseExportLog`` were both created directly
        # on the live database, outside this migration history, so this migration
        # originally adopted BOTH into migration *state* only
        # (``database_operations=[]``).
        #
        # That was right for CaseExportLog and wrong for two_stage. State-only
        # adoption tells Django "the database already has this", which is true of
        # the one server that was patched by hand and false of every database
        # built from scratch. Migration 0009 then reads CaseForm through the
        # frozen state — which includes two_stage — and aborts with
        # "no such column: cases_caseform.two_stage", so no fresh install could
        # ever be provisioned from the migration history at all.
        #
        # The AddField below is therefore issued against the database as well.
        # Editing an already-applied migration is safe here and is the reason
        # this is the correct place for the fix: Django records applied
        # migrations by name and never re-runs them, so every existing database
        # (which has 0003 applied and the column present) is untouched, while a
        # new database now gets the column it was always missing.
        #
        # CaseExportLog stays state-only on purpose — migration 0008 creates that
        # table when it is absent, which covers the fresh-install case for it.
        migrations.AddField(
            model_name='caseform',
            name='two_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CaseExportLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('form_kind', models.CharField(blank=True, max_length=10)),
                        ('form_version', models.IntegerField(blank=True, null=True)),
                        ('side', models.CharField(blank=True, max_length=10)),
                        ('fmt', models.CharField(blank=True, max_length=20)),
                        ('label', models.CharField(blank=True, max_length=120)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_exports', to=settings.AUTH_USER_MODEL)),
                        ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='cases.case')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('rial_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_builtin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
