# Generated by Django 5.2.7 on 2026-08-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add ``cases_caseseen`` — the per-person read receipt behind the NEW badge.

    A new table only: no existing table, column or row is touched, and nothing
    that already exists changes behaviour. Until a person opens a case there is
    no row for it, so on the deploy that runs this migration every case already
    sitting in somebody's inbox reads as NEW once — the marker then settles as
    people work through their inboxes. Deliberately not backfilled: guessing a
    "seen" time for a case nobody has actually opened would hide exactly the
    arrivals the badge exists to point at.

    The unique constraint on (case, user) is load-bearing, not just hygiene — it
    is what makes the upsert in ``cases.services.mark_case_seen`` safe when two
    browser tabs open the same case at the same instant.
    """

    dependencies = [
        ('cases', '0012_caseform_two_stage_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_marks', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_seen_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('case', 'user')},
            },
        ),
    ]
