# Generated by Django 5.2.7 on 2026-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_caseseen_new_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseform',
            name='export_terms',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
