# Generated by Django 5.2.7 on 2026-08-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_caseform_export_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='marketing_label',
            field=models.CharField(blank=True, choices=[('sponsor', 'سرمایه\u200cگذار — SPONSOR / INVESTOR'), ('owner', 'کارفرمای اصلی — OWNER / CLIENT'), ('pmt', 'مجری طرح — PMT — PROJECT MGMT TEAM'), ('mc', 'مدیریت طرح — MC / PMC — MGMT CONTRACTOR'), ('licensor', 'لیسانسور — LICENSOR'), ('design', 'مشاور طراح — DESIGN CONSULTANT — FEED / DED'), ('supervision', 'مشاور نظارت — SUPERVISION'), ('c', 'پیمانکار اجرا — C — CONSTRUCTION ONLY'), ('p', 'پیمانکار خرید — P — PROCUREMENT ONLY'), ('pc', 'پیمانکار خرید و اجرا — PC — PROCUREMENT + CONSTRUCTION'), ('epc', 'پیمانکار طرح، خرید و اجرا — EPC — ENG. PROC. CONSTRUCTION'), ('sub', 'پیمانکار جزء — SUBCONTRACTOR')], default='', max_length=32),
        ),
    ]
