# Generated by Django 5.2.7 on 2026-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_alter_case_marketing_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='marketing_label',
            field=models.CharField(blank=True, choices=[('sponsor', 'سرمایه\u200cگذار — SPONSOR / INVESTOR'), ('owner', 'کارفرمای اصلی — OWNER / CLIENT'), ('pmt', 'مجری طرح — PMT — PROJECT MGMT TEAM'), ('mc', 'مدیریت طرح — MC / PMC — MGMT CONTRACTOR'), ('licensor', 'لایسنسور — LICENSOR'), ('design', 'مشاور طراح — DESIGN CONSULTANT — FEED / DED'), ('supervision', 'مشاور نظارت — SUPERVISION'), ('c', 'پیمانکار اجرا — C — CONSTRUCTION ONLY'), ('p', 'پیمانکار خرید — P — PROCUREMENT ONLY'), ('pc', 'پیمانکار خرید و اجرا — PC — PROCUREMENT + CONSTRUCTION'), ('epc', 'پیمانکار طرح، خرید و اجرا — EPC — ENG. PROC. CONSTRUCTION'), ('sub', 'پیمانکار جزء P — SUBCONTRACTOR — P'), ('sub_pc', 'پیمانکار جزء PC — SUBCONTRACTOR — PC'), ('sub_epc', 'پیمانکار جزء EPC — SUBCONTRACTOR — EPC')], default='', max_length=32),
        ),
    ]
