# Generated by Django 5.2.7 on 2026-09-11 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_case_marketing_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='purchasing_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='warehouse_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WITH_TECHNICAL', 'With Technical'), ('RETURNED_TO_COMMERCIAL', 'Returned to Commercial'), ('WITH_SUPPLY', 'With Supply'), ('RETURNED_TO_TECHNICAL', 'Returned to Technical'), ('WITH_COMMERCIAL', 'With Commercial (final)'), ('UNSUP_PEND_SUP', 'Cannot supply — awaiting Supply manager'), ('UNSUP_PEND_COM', 'Cannot supply — awaiting Commercial manager'), ('UNSUPPLIABLE', 'Cannot supply'), ('UNSUP_CLOSED', 'Cannot supply'), ('PENDING_CANCEL', 'Cancel — pending approval'), ('CLOSED', 'Closed / Sent to client'), ('FINAL_APPROVED', 'Final Approved'), ('FINAL_CLOSED', 'Final Closed'), ('BURNED', 'Burned'), ('CANCELLED', 'Cancelled'), ('WITH_WAREHOUSE', 'With Warehouse')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Case created'), ('SUBMIT_TO_TECHNICAL', 'Submitted to Technical'), ('RETURN_TO_COMMERCIAL', 'Returned to Commercial'), ('ASSIGN', 'Assigned to expert'), ('DELEGATE', 'Delegated'), ('SEND_TO_SUPPLY', 'Submitted to Supply'), ('RETURN_TO_TECHNICAL', 'Returned to Technical'), ('SEND_TO_COMMERCIAL', 'Submitted to Commercial'), ('BUILD_TO', 'TO form built'), ('BUILD_PI', 'PI form built'), ('NEW_VERSION', 'New form version'), ('EDIT', 'Edited'), ('COMMENT', 'Comment added'), ('CLOSE', 'Closed — sent to client'), ('CANNOT_SUPPLY', 'Marked cannot supply'), ('APPROVE_UNSUPPLIABLE', 'Cannot-supply approved'), ('REJECT_UNSUPPLIABLE', 'Cannot-supply rejected'), ('RETURN_TO_SUPPLY', 'Returned to Supply'), ('FINALIZE', 'Final Approved'), ('REQUEST_CANCEL', 'Cancellation requested'), ('APPROVE_CANCEL', 'Cancellation approved'), ('REJECT_CANCEL', 'Cancellation rejected'), ('CANCEL', 'Cancelled'), ('BURN', 'Burned'), ('FINAL_CLOSE', 'Final Closed'), ('BUILD_PURCHASE_INVOICE', 'Purchase Invoice built'), ('SEND_TO_WAREHOUSE', 'Submitted to Warehouse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='form_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='caseexportlog',
            name='form_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='caseform',
            name='kind',
            field=models.CharField(choices=[('INQUIRY', 'Inquiry'), ('TO', 'Technical Offer (TO)'), ('PI', 'Proforma Invoice (PI)'), ('PURCHASE_INVOICE', 'Purchase Invoice')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
