# Generated by Django 5.2.7 on 2026-08-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('sponsor', 'سرمایه\u200cگذار'), ('owner', 'کارفرمای اصلی'), ('project', 'نام پروژه'), ('phase', 'فاز پروژه'), ('pmt', 'مجری طرح'), ('mc', 'مدیریت طرح'), ('licensor', 'لیسانسور'), ('design', 'مشاور طراح'), ('supervision', 'مشاور نظارت'), ('c', 'پیمانکار اجرا'), ('p', 'پیمانکار خرید'), ('pc', 'پیمانکار خرید و اجرا'), ('epc', 'پیمانکار طرح، خرید و اجرا'), ('sub', 'پیمانکار جزء'), ('tpi', 'بازرس ثالث'), ('laboratory', 'آزمایشگاه'), ('us', 'موقعیت ما'), ('supplier', 'تأمین\u200cکننده'), ('rival', 'رقیب احتمالی')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='marketing.entity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='marketing.entity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('field', 'name'), name='marketing_entity_unique_field_name'),
        ),
        migrations.AddConstraint(
            model_name='entitylink',
            constraint=models.UniqueConstraint(fields=('entity_a', 'entity_b'), name='marketing_link_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='entitylink',
            constraint=models.CheckConstraint(condition=models.Q(('entity_a', models.F('entity_b')), _negated=True), name='marketing_link_no_self'),
        ),
    ]
