# Generated by Django 5.2.7 on 2026-08-31 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0015_case_marketing_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('sponsor', 'سرمایه\u200cگذار — SPONSOR / INVESTOR'), ('owner', 'کارفرمای اصلی — OWNER / CLIENT'), ('pmt', 'مجری طرح — PMT — PROJECT MGMT TEAM'), ('mc', 'مدیریت طرح — MC / PMC — MGMT CONTRACTOR'), ('licensor', 'لیسانسور — LICENSOR'), ('design', 'مشاور طراح — DESIGN CONSULTANT — FEED / DED'), ('supervision', 'مشاور نظارت — SUPERVISION'), ('c', 'پیمانکار اجرا — C — CONSTRUCTION ONLY'), ('p', 'پیمانکار خرید — P — PROCUREMENT ONLY'), ('pc', 'پیمانکار خرید و اجرا — PC — PROCUREMENT + CONSTRUCTION'), ('epc', 'پیمانکار طرح، خرید و اجرا — EPC — ENG. PROC. CONSTRUCTION'), ('sub', 'پیمانکار جزء — SUBCONTRACTOR')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_labels', to='cases.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'client__name'],
                'constraints': [models.UniqueConstraint(fields=('client', 'label', 'created_by'), name='marketing_clientlabel_unique_per_owner')],
            },
        ),
    ]
