# Generated by Django 5.2.7 on 2026-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_clientlabel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlabel',
            name='label',
            field=models.CharField(choices=[('sponsor', 'سرمایه\u200cگذار — SPONSOR / INVESTOR'), ('owner', 'کارفرمای اصلی — OWNER / CLIENT'), ('pmt', 'مجری طرح — PMT — PROJECT MGMT TEAM'), ('mc', 'مدیریت طرح — MC / PMC — MGMT CONTRACTOR'), ('licensor', 'لیسانسور — LICENSOR'), ('design', 'مشاور طراح — DESIGN CONSULTANT — FEED / DED'), ('supervision', 'مشاور نظارت — SUPERVISION'), ('c', 'پیمانکار اجرا — C — CONSTRUCTION ONLY'), ('p', 'پیمانکار خرید — P — PROCUREMENT ONLY'), ('pc', 'پیمانکار خرید و اجرا — PC — PROCUREMENT + CONSTRUCTION'), ('epc', 'پیمانکار طرح، خرید و اجرا — EPC — ENG. PROC. CONSTRUCTION'), ('sub', 'پیمانکار جزء P — SUBCONTRACTOR — P'), ('sub_pc', 'پیمانکار جزء PC — SUBCONTRACTOR — PC'), ('sub_epc', 'پیمانکار جزء EPC — SUBCONTRACTOR — EPC'), ('rival', 'رقیب احتمالی — COMPETITOR'), ('supplier', 'تأمین\u200cکننده — SUB-SUPPLIER')], max_length=32),
        ),
    ]
