# Generated by Django 5.2.7 on 2026-09-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_alter_case_marketing_label'),
        ('marketing', '0004_alter_clientlabel_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_role', models.CharField(max_length=32)),
                ('target_role', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anchor_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='cases.client')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_connections', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='cases.client')),
            ],
            options={
                'ordering': ['anchor_client__name', 'anchor_role', 'target_role'],
                'constraints': [models.UniqueConstraint(fields=('anchor_client', 'anchor_role', 'target_client', 'target_role', 'case'), name='marketing_connection_unique_edge')],
            },
        ),
    ]
