# Generated by Django 5.2.7 on 2026-09-02 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_case_marketing_label'),
        ('marketing', '0006_clear_manual_marketing_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlabel',
            name='label',
            field=models.CharField(choices=[('sponsor', 'سرمایه\u200cگذار — SPONSOR / INVESTOR'), ('owner', 'کارفرمای اصلی — OWNER / CLIENT'), ('pmt', 'مجری طرح — PMT — PROJECT MGMT TEAM'), ('mc', 'مدیریت طرح — MC / PMC — MGMT CONTRACTOR'), ('licensor', 'لایسنسور — LICENSOR'), ('design', 'مشاور طراح — DESIGN CONSULTANT — FEED / DED'), ('supervision', 'مشاور نظارت — SUPERVISION'), ('c', 'پیمانکار اجرا — C — CONSTRUCTION ONLY'), ('p', 'پیمانکار خرید — P — PROCUREMENT ONLY'), ('pc', 'پیمانکار خرید و اجرا — PC — PROCUREMENT + CONSTRUCTION'), ('epc', 'پیمانکار طرح، خرید و اجرا — EPC — ENG. PROC. CONSTRUCTION'), ('sub', 'پیمانکار جزء P — SUBCONTRACTOR — P'), ('sub_pc', 'پیمانکار جزء PC — SUBCONTRACTOR — PC'), ('sub_epc', 'پیمانکار جزء EPC — SUBCONTRACTOR — EPC'), ('rival', 'رقیب احتمالی — COMPETITOR'), ('supplier', 'تأمین\u200cکننده — SUB-SUPPLIER'), ('project', 'نام پروژه — PROJECT'), ('phase', 'فاز پروژه — PROJECT PHASE'), ('tpi', 'بازرس ثالث — TPI — THIRD PARTY INSP.'), ('laboratory', 'آزمایشگاه — LABORATORY')], max_length=32),
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CLIENT_REGISTERED', 'Company registered'), ('LABEL_ADDED', 'Label added'), ('LABEL_REMOVED', 'Label removed'), ('CONNECTION_ADDED', 'Connection added'), ('CONNECTION_REMOVED', 'Connection removed'), ('CONTACT_ADDED', 'Contact added'), ('CONTACT_REMOVED', 'Contact removed')], max_length=32)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('actor_name', models.CharField(blank=True, max_length=160)),
                ('actor_role_label', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_client_events', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_events', to='cases.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('MALE', 'آقای — MALE'), ('FEMALE', 'خانم — FEMALE')], max_length=10)),
                ('phone_prefix', models.CharField(blank=True, max_length=16)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('phone_ext', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_contacts', to='cases.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='marketing.contactrole')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
