# Generated by Django 5.2.7 on 2026-09-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_case_marketing_label'),
        ('marketing', '0007_alter_clientlabel_label_clientevent_contactrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='subject_role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='clientevent',
            name='action',
            field=models.CharField(choices=[('CLIENT_REGISTERED', 'Company registered'), ('LABEL_ADDED', 'Label added'), ('LABEL_REMOVED', 'Label removed'), ('CONNECTION_ADDED', 'Connection added'), ('CONNECTION_REMOVED', 'Connection removed'), ('CONTACT_ADDED', 'Contact added'), ('CONTACT_REMOVED', 'Contact removed'), ('REPORT_ADDED', 'Report added')], max_length=32),
        ),
        migrations.CreateModel(
            name='ReportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_reports', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_reports', to='cases.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('options', models.ManyToManyField(blank=True, related_name='reports', to='marketing.reportoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
