# Generated by Django 5.2.7 on 2026-09-02 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_case_marketing_label'),
        ('marketing', '0008_clientevent_subject_role_alter_clientevent_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Dealt with')], default='OPEN', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_reminders', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_reminders', to='cases.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'pk'],
                'indexes': [models.Index(fields=['owner', 'state', 'due_at'], name='marketing_reminder_due_idx')],
            },
        ),
    ]
