# Generated by Django 5.2.7 on 2026-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='action',
            field=models.CharField(choices=[('CLIENT_REGISTERED', 'Company registered'), ('LABEL_ADDED', 'Label added'), ('LABEL_REMOVED', 'Label removed'), ('CONNECTION_ADDED', 'Connection added'), ('CONNECTION_REMOVED', 'Connection removed'), ('CONTACT_ADDED', 'Contact added'), ('CONTACT_REMOVED', 'Contact removed'), ('REPORT_ADDED', 'Report added'), ('CASE_ROLE_CHANGED', 'Case role changed')], max_length=32),
        ),
    ]
