# Generated by Django 5.2.7 on 2026-09-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_case_marketing_label'),
        ('marketing', '0014_remove_companycontact_phone_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreport',
            name='reminder_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='reminder_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='reminder_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_reports', to='cases.client'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_reminders', to='cases.client'),
        ),
    ]
