# Generated by Django 5.2.6 on 2026-06-29 12:19

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_general_manager', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial'), ('TECHNICAL', 'Technical'), ('SUPPLY', 'Supply')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('EXPERT', 'Expert')], max_length=20)),
                ('supply_kind', models.CharField(blank=True, choices=[('INTERNAL', 'Internal Supply'), ('EXTERNAL', 'External Supply')], max_length=20)),
                ('internal_code', models.CharField(blank=True, max_length=40, verbose_name='Internal code')),
                ('org_number', models.CharField(blank=True, max_length=40, verbose_name='Organisational number')),
                ('org_title', models.CharField(blank=True, help_text='For example: Sales Expert, Technical Manager …', max_length=120, verbose_name='Organisational title')),
                ('signature', models.ImageField(blank=True, help_text='Signature image stamped on approved forms.', null=True, upload_to=accounts.models.signature_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
