# Generated by Django 5.2 on 2026-07-12 06:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_platformconfig_vat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stamp',
            field=models.ImageField(blank=True, help_text='Company/personal stamp (مهر) stamped on approved forms.', null=True, upload_to=accounts.models.stamp_upload_path),
        ),
    ]
