# Generated by Django 5.2.7 on 2026-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='default_reconnect_grace_seconds',
            field=models.PositiveIntegerField(default=900, help_text='Default reconnect time in seconds (e.g. 900 = 15:00).'),
        ),
    ]
