# Generated by Django 5.2.7 on 2026-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_presence_gap_and_grace_bump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Supervisor'), ('SUPERVISOR', 'Observer'), ('EXPERT', 'Expert')], max_length=20),
        ),
    ]
