# Generated by Django 5.2.7 on 2026-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial'), ('TECHNICAL', 'Technical'), ('SUPPLY', 'Supply'), ('MARKETING', 'Marketing'), ('PURCHASING', 'Purchasing'), ('WAREHOUSE', 'Warehouse'), ('QC', 'Quality Control')], max_length=20),
        ),
    ]
