# Generated by Django 5.2.6 on 2026-06-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=40, unique=True)),
                ('tech_start', models.CharField(blank=True, default='', max_length=8)),
                ('tech_group', models.CharField(blank=True, default='', max_length=8)),
                ('item_start', models.CharField(blank=True, default='', max_length=8)),
                ('item_group', models.CharField(blank=True, default='', max_length=8)),
                ('item_seq_digits', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=40, unique=True)),
                ('columns', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='CodeTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=40)),
                ('row_no', models.PositiveIntegerField()),
                ('cells', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['row_no'],
                'indexes': [models.Index(fields=['group', 'row_no'], name='itemcoder_c_group_103b55_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=40)),
                ('feature', models.CharField(db_index=True, max_length=80)),
                ('value', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['group', 'feature', 'code'],
                'indexes': [models.Index(fields=['group', 'feature'], name='itemcoder_f_group_95c4eb_idx')],
                'unique_together': {('group', 'feature', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GroupFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('main', 'Main'), ('sub', 'Sub'), ('info', 'Info')], default='main', max_length=8)),
                ('in_small_code', models.BooleanField(default=False)),
                ('small_order', models.PositiveSmallIntegerField(default=0)),
                ('column_index', models.IntegerField(default=-1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'position', 'name'],
                'indexes': [models.Index(fields=['group', 'position'], name='itemcoder_g_group_77a53a_idx')],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('currency', models.CharField(default='rial', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='itemcoder_c_key_d316e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='itemcoder.pricelist')),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'price_list'], name='itemcoder_c_code_3dec16_idx')],
                'unique_together': {('price_list', 'code')},
            },
        ),
    ]
