# Generated by Django 5.2.7 on 2026-08-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_seat_tenure_eventlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seattenure',
            new_name='people_seat_source__be81ce_idx',
            old_name='people_seat_source__7c2a1d_idx',
        ),
    ]
