# Generated by Django 5.x on 2026-08-02
from datetime import time

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_remove_auto_tech_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="children",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="person",
            name="children_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="work_start",
            field=models.TimeField(
                blank=True,
                default=time(8, 0),
                help_text="Daily shift start (local timezone).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="work_end",
            field=models.TimeField(
                blank=True,
                default=time(17, 0),
                help_text="Daily shift end (local timezone).",
                null=True,
            ),
        ),
    ]
