# Generated by Django 5.2.7 on 2026-08-09 08:31
#
# Three unrelated corrections that the autodetector emits as one file:
#   * shiftdaylog.carry_seconds — sub-minute presence banked between pings.
#   * person.work_start / work_end — the columns were added in 0011 with a
#     08:00/17:00 fill value while the model has said default=None ever since,
#     so the graph has been permanently one migration behind. No column changes
#     shape here; a field default never reaches the database.
#   * the request-code unique index gains a condition so the blank default is
#     not treated as a value that must be unique.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_staffrequest_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffrequest',
            name='people_staffrequest_request_code_uniq',
        ),
        migrations.AddField(
            model_name='shiftdaylog',
            name='carry_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_end',
            field=models.TimeField(blank=True, default=None, help_text='Daily shift end (defaults to 17:00 when empty).', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_start',
            field=models.TimeField(blank=True, default=None, help_text='Daily shift start (defaults to 08:00 when empty).', null=True),
        ),
        migrations.AddConstraint(
            model_name='staffrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_code', ''), _negated=True), fields=('request_code',), name='people_staffrequest_request_code_uniq'),
        ),
    ]
