# Generated by Django 5.2.7 on 2026-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_shiftdaylog_away_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdaylog',
            name='idle_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='reconnect_grace_seconds',
            field=models.PositiveIntegerField(default=900, help_text='Reconnect time after disconnect, in seconds (default 15:00).'),
        ),
    ]
