# Generated by Django 5.2.7 on 2026-09-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_seed_presence_gap_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfDayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.DateField(db_index=True)),
                ('requests_for_supervisor', models.JSONField(blank=True, default=list)),
                ('ideas_for_today', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_reports', to='people.person')),
            ],
            options={
                'ordering': ['-work_day', '-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('person', 'work_day'), name='people_eodreport_unique_person_day')],
            },
        ),
    ]
